/**
 * Scriptos API
 * The API Specification for the Scriptos Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorResponse { 
    message?: string;
    code?: string;
}

