openapi: 3.1.0
info:
  title: Scriptos API
  description: The API Specification for the Scriptos Backend
  version: 1.0.0
paths:
  /register:
    post:
      operationId: userRegister
      summary: Register a new Scriptos user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/registerRequest"
      responses:
        200:
          description: OK

  /login:
    get:
      operationId: userLogin
      summary: Login as an existing Scriptos user
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/loginRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tokenResponse"

  /group:
    post:
      operationId: createGroup
      summary: Create a new Scriptos group
      tags:
        - Groups
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createGroupRequest"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/groupIdResponse"

components:
  schemas:
    registerRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    loginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string

    tokenResponse:
      type: object
      properties:
        token:
          type: string

    errorResponse:
      type: object
      properties:
        message:
          type: string
        code:
          type: string

    createGroupRequest:
      type: object
      required:
        - name
      properties:
        name:
          type: string

    groupIdResponse:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
