spring:
  application:
    name: scriptos-server
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/scriptos
  servlet:
    multipart:
      max-file-size: 5GB

springdoc:
  swagger-ui:
    path: /api-docs

server:
  port: 8080
scriptos:
  auth:
    unused-token-expiration: 2800
    auth-request-delay: 1000
  groups:
    common-group-name: common
  storage:
    directory: scriptos-data
    accepted-extensions:
      - PNG
      - PDF
      - JPG
      - TXT
  admin:
    username: admin
    password: piotr2005